config/routes.rb
Rails.application.routes.draw do
 
  devise_for :employees, controllers: {
    :registrations => 'employees/registrations',
    :sessions => 'employees/sessions',
    :passwords => 'employees/passwords'
  }
  resources :attendances do
    collection do
      get :week
      post :check
      post :orders
    end
  end
  resources :patterns
  resources :seals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee

  has_many :attendance_details, :dependent => :destroy
  accepts_nested_attributes_for :attendance_details

  def self.select_attendance_by_date(date)
    self.where(base_date: (date.beginning_of_day)..(date.end_of_day))
  end
  
  # 基準日から勤怠を検索する。
  def self.select_at(dt,format)
    {
      month: self.where(base_date: dt.beginning_of_month..dt.end_of_month),
      week: self.where(base_date: dt.beginning_of_week..dt.end_of_week),
      day: self.where(base_date: dt.beginning_of_day..dt.end_of_day)
    }[format]
  end

  # テーブル結合
  def self.join_table(table_names)
    self.includes(table_names).references(table_names)
  end
  
  # 月間勤怠レコード
  def self.monthly_attendance_record(dt)
    self.select_at(dt,:month).join_table(:attendance_details)
  end

  # Todo
  # 引数：なし
  # 返り値：
  # total: 
  #   {work_time,break_time,operating,
  #     paid_time,special_paid_time,
  #     actual_time,deducation_time}
  # 作業,休憩,稼働,有給(一般),有給(特別),実働,控除
  # を持ったオブジェクトを返す。
  # Selfから勤怠レコードｓの合計時間を集計する。
  def self.aggregate_time
    result = {}
    # シンボル毎にresultに代入していく
    [:break_time,:operating_time,:paid_time,
      :special_paid_time,:deduction_time].each do |symbol|
        div, mod = self.all.sum(symbol).divmod(60)
        result[symbol] = (div+(mod/60.0)).floor(2)
    end

    # work_time,actual_time 
    nil_operating_time = self.where.not(operating_time: nil).all.sum(:break_time)

    div, mod = nil_operating_time.divmod(60)

    result[:work_time] = result[:operating_time].to_f+(div+(mod/60.0)).floor(2)

    result[:actual_time] = result[:operating_time].to_f+result[:paid_time].
      to_f+result[:special_paid_time].to_f
    

    return result
  end

  # 引数: 日付
  # 返り値：オブジェクト配列
  # 例）オブジェクト配列
  # [{start_time,end_time,work_time,beak_time...},{start_time,end_time...}]

  # ～に勤怠データを加工する。
  # 月勤怠画面用のデータを加工する。
  # ※勤怠がない日にちも空文字入れて必ず、１～月末までデータをモデル側で作っておく。
  def self.process_in_month(current)
    # 1. 必要なデータ:開始時間、終了時間、作業,休憩,稼働,有給(一般),有給(特別),実働,控除、摘要（勤怠詳細オーダーIDの結合）
    # 2. 以上のデータを2次元マトリックスに加工する。
    # 例）
    # [{start_time:Tue, 28 Jun 2022 09:47:29 JST +09:00,end_time:Tue, 28 Jun 2022 18:47:29 JST +09:00...},
    # {start_time:'',end_time:''...}]
    # 何もない日は、空文字（''）を入れる

    result = []
    (current.to_datetime.beginning_of_month..current.to_datetime.end_of_month).each do |day|
        result.push({
          start_time:'',
          end_time:'',
          working_time:"",
          break_time:"",
          operating_time:'',
          paid_time:'',
          special_paid_time:'',
          actual_time:'',
          deduction_time:'',
          remarks: ''
        })
    end

    self.all.each do |j_attendance|

      day = j_attendance.base_date.day

      result[day-1] = { 

        start_time:j_attendance.start_time,

        end_time:j_attendance.end_time,

        working_time:      minutes_to_hour_and_decmltime(j_attendance.operating_time.to_i+
          (j_attendance.operating_time.nil? ? 0.00 : j_attendance.break_time.to_i)),

        break_time:        minutes_to_hour_and_decmltime(j_attendance.break_time.to_i),

        operating_time:    minutes_to_hour_and_decmltime(j_attendance.operating_time.to_i),

        paid_time:         minutes_to_hour_and_decmltime(j_attendance.paid_time.to_i),

        special_paid_time: minutes_to_hour_and_decmltime(j_attendance.special_paid_time.to_i),

        actual_time:       minutes_to_hour_and_decmltime(j_attendance.operating_time.to_i+j_attendance.paid_time.to_i+j_attendance.special_paid_time.to_i),

        deducation_time:    minutes_to_hour_and_decmltime(j_attendance.deduction_time.to_i),

        remarks: j_attendance.attendance_details.join_work_contents

      }
    end

    result
    
  end

  # Todo（7/1以降着手）
  # 週勤怠へ勤怠レコードｓを加工する。
  def self.process_in_week

  end

  # 勤怠詳細から勤怠へ時間内訳と開始・終了時刻と整合性フラグを算出して保存する処理
  def self.calc_times_and_consistency_flg_and_save(attendance_details)
    save_data = {
      start_time:nil,end_time:nil,break_time:"",
      operating_time:'',paid_time:'',special_paid_time:'',
      deduction_time:'',consistency_flg: false
    }
    # 時間内訳計算
    [['稼働時間',0,:operating_time],['休憩時間',1,:break_time],['控除時間',2,:deduction_time],
    ['一般有給',3,:paid_time],['特別有給',4,:special_paid_time]].each do |t_detail,itemized_time,symbol|
      orders = Order.where(itemized_time: itemized_time)
      # オーダーからdetailsを検索。ヒットした分の時間を足し合わせる
      save_data[symbol] = attendance_details.where(order_id: orders.ids).
        map{|r| (r.end_time.hour-r.start_time.hour)*60+(r.end_time.min-r.start_time.min).abs}.sum
    end

    #　開始・終了時間
    orderd_r = attendance_details.order(start_time: "ASC")
    save_data[:start_time] = orderd_r.first.start_time
    save_data[:end_time] = orderd_r.last.end_time

    # 整合性フラグ
    # Todo 警告バリデーションチェッカーを使う。
    # 2022/06/30現在、保存時trueにしておく。
    save_data[:consistency_flg] = true
    # save
    Attendance.find(attendance_details.first.attendance_id).update!(save_data)
  end


  def self.valid_check(holidays)
    result = nil
    error_message = {valid_error: "登録された以下の日付の勤怠データに不整合があります。"}

    holidays_a = holidays.map{|h|h.date.day}
    
    self.all.each do |attendance|

      if holidays_a.include?(attendance.base_date.day)

        week = ['日','月','火','水','木','金','土'][attendance.base_date.wday]

        error_message["err_date-#{attendance.base_date.day}".to_sym] = attendance.base_date.strftime("%Y/%m/%d(#{week})")

        result = true

      end
    end

    result ? error_message.to_a : {success: "確認が取れました。帳票出力して下さい。"}.to_a
  end



  # ************** private ******************
  # 2022/06/28 月勤怠フィルタは良好。（週勤怠未実装）
  # 引数：(string)month_attendance|week_attendance
  # 返り値：（フィルタされた）勤怠レコードｓ

  # 画面ごとに勤怠から必要なデータのみを選出する。
  def self.filter_by(page_name)
    self.select(nessarry_colmun_of(page_name))
  end

  # 引数：画面名
  # 返り値：シンボル配列
  def self.nessarry_colmun_of(page_name)
    {
      'month_attendance': [:start_time, :end_time, :break_time, :operating_time, 
        :paid_time, :special_paid_time, :deduction_time, :work_content],
      'week_attendance': []
    }[page_name]
  end

  def self.minutes_to_hour_and_decmltime(minutes)
    div, mod = minutes.divmod(60)
    sprintf("%0.2f",(div+(mod/60.0).floor(2)))
  end

  private_class_method :filter_by, :nessarry_colmun_of
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index

    @orders = Order.all

    @month = params['date'].blank? ? 
      Time.current : Time.parse(params['date'])

    @nav_prev = @month.prev_month.strftime("%Y/%m")

    @nav_next = @month.next_month.strftime("%Y/%m")

    @attendances = @emp.attendances.monthly_attendance_record(@month).
      order(base_date: "ASC").process_in_month(@month)

    @sum = @emp.attendances.select_at(@month,:month).aggregate_time

  end

  def check
    @month = params['date'].blank? ? 
      Time.current : Time.parse(params['date'])
      
    @errors = @emp.attendances.monthly_attendance_record(@month).
      valid_check(BusinessCalendar.public_holidays(@month))

    respond_to do |format|
      format.html
      format.js
    end

  end

  def orders
    @month = params['date'].blank? ? 
    Time.current : Time.parse(params['date'])
    
    orders = params.require(:attendance_detail).permit(orders: {})
    
    order_ids = orders[:orders].values.reject{|v| v.blank?}
    
    attd_arr = @emp.attendances.monthly_attendance_record(@month).order(base_date: "ASC").
    filter{|r| r.attendance_details.where(order_id: order_ids).length > 0}
    
    @attendances = Attendance.where(id: attd_arr.map{ |attd| attd.id}).
        process_in_month(@month)
    
    @sum = @emp.attendances.select_at(@month,:month).aggregate_time

      respond_to do |format|
        format.html
        format.js
      end
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end
  
  def week
  end

  # GET /attendances/new
  def new
    @current = params['date'].blank? ? 
      Time.current : Time.parse(params['date'])
    @nav_prev = @current.prev_day.strftime("%Y/%m/%d")
    @nav_next = @current.next_day.strftime("%Y/%m/%d")
    @orders = Order.all
    @works  = Work.all

    if((ada = @emp.attendances.select_attendance_by_date(@current).first).nil?)
      @attendance = @emp.attendances.build
      @ada_details = @attendance.attendance_details.init_attendance_detail(@attendance.id)

    else
      @attendance = ada
      @ada_details = ada.attendance_details.init_attendance_detail(@attendance.id)

    end
    @errors = errors = AttendanceDetail.valid?(@attendance.attendance_details)

    if ((warning = AttendanceDetail.warning?(@attendance.attendance_details)).length > 0)
      @errors += warning
    end
  end

  # GET /attendances/1/edit
  def edit
    @orders = Order.all
    @works  = Work.all
  end

  # POST /attendances or /attendances.json
  def create

    @attendance = Attendance.new(filter_with_filled_form)
    if ((errors = AttendanceDetail.valid?(@attendance.attendance_details)).length) > 0
      flash.now[:errors] = errors
    end

    if ((warning = AttendanceDetail.warning?(@attendance.attendance_details)).length > 0)
      flash[:warning] = warning
    end

    ActiveRecord::Base.transaction do
        if @attendance.save
          Attendance.calc_times_and_consistency_flg_and_save(@attendance.attendance_details)
          flash[:success] = '登録に成功しました。'
          redirect_to new_attendance_path(date: @attendance.base_date)
        else
          render :new
        end
      end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    @orders = Order.all
    @works  = Work.all
    @errors = errors = AttendanceDetail.valid?(@attendance.attendance_details)

    if ((warning = AttendanceDetail.warning?(@attendance.attendance_details)).length > 0)
      @errors += warning
    end
    ActiveRecord::Base.transaction do
      if errors.length < 1 && @attendance.update!(filter_with_filled_form)
        Attendance.calc_times_and_consistency_flg_and_save(@attendance.attendance_details)
        @errors = [['success', '登録に成功しました。']]
      end
      redirect_to action: :new, date: @attendance.base_date
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy

    dt = Time.parse(Regexp.new('\d{4}-\d{2}-\d{2}').match(request.referer)[0])

    attendance = Attendance.find_by(id: params[:id])

    attendance.destroy if attendance

    @attendance = @emp.attendances.build(base_date: dt)

    @ada_details = @attendance.attendance_details.init_attendance_detail(@attendance.id)

    redirect_to action: :new, date: dt

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:corporation_id, :employee_id, :start_time, :end_time, :rest_time, :work_content)
    end

    def create_attendance_params
      params.require(:attendance).permit(:id, :employee_id, :base_date, attendance_details_attributes: [:id, :start_time, :end_time, :order_id, :work_id, :work_content])
    end

    def filter_with_filled_form
      result = create_attendance_params
      result[:attendance_details_attributes] = result[:attendance_details_attributes].select{|k,v|!v[:start_time].blank?&&!v[:end_time].blank?}
      result
    end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def itemized_time_hash
    result = {}
    Order.all.each do |order|
      result[order.id] = order.itemized_time
    end
    result
  end
end

app/views/attendances/_print.html.erb
<div id="print_area">
    <% unless attendances.blank? %>
    <div class="mx-4">
        <table class="table table-hover table-sm text-center">
            <thead>
                <tr>
                    <th rowspan="2" width="2%" class="pb">日</th>
                    <th rowspan="2" width="2%" class="pb2">曜日</th>
                    <th rowspan="2", colspan="3" width="12%" class="pb">時刻</th>
                    <th colspan="7" width="42%" class="border-bottom">時間内訳</th>
                    <th rowspan="2" width="42%" class="pb">摘要</th>
                </tr>
                <tr>
                    <th class="border-top">作業</th>
                    <th class="border-top">休憩</th>
                    <th class="border-top">稼働</th>
                    <th class="border-top">有給(一般)</th>
                    <th class="border-top">有給(特別)</th>
                    <th class="border-top">実働</th>
                    <th class="border-top">控除</th>
                </tr>
            </thead>
            <tbody>
                <% (@month.to_datetime.beginning_of_month..@month.to_datetime.end_of_month).each do |month| %>
                    <tr class="<%= "today" if month.today? %>">
                        <td width="2%" class="holiday <%= "sat" if month.saturday? %> <%= "sun" if month.sunday? %>">
                            <%= format_to(month,:day) %>
                        </td>
                        <td width="2%" class="<%= "sat" if month.saturday? %> <%= "sun" if month.sunday? %>">
                            <%= format_to(month,:wday) %>
                        </td>
                        <td width="5%"><%= format_to(attendances[month.day-1][:start_time],:am_pm)%></td>
                        <td width="2%">～</td>
                        <td width="5%"><%= format_to(attendances[month.day-1][:end_time],:am_pm)%></td>
                        <td width="7%"><%=attendances[month.day-1][:working_time] %></td>
                        <td width="7%"><%=attendances[month.day-1][:break_time] %></td>
                        <td width="7%"><%=attendances[month.day-1][:operating_time] %></td>
                        <td width="7%"><%=attendances[month.day-1][:paid_time] %></td>
                        <td width="7%"><%=attendances[month.day-1][:special_paid_time] %></td>
                        <td width="7%"><%=attendances[month.day-1][:actual_time] %></td>
                        <td width="7%"><%=attendances[month.day-1][:deducation_time] %></td>
                        <td width="42%"><%= attendances[month.day-1][:remarks] %></td>
                    </tr>
                <% end %>
                <!-- 勤怠時間の集計表示 -->
                <tr>
                    <td colspan="5">合計</td>
                    <td colspan="1"><%= @sum[:work_time] %></td>
                    <td colspan="1"><%= (@sum[:break_time]) %></td>
                    <td colspan="1"><%= (@sum[:operating_time]) %></td>
                    <td colspan="1"><%= (@sum[:paid_time]) %></td>
                    <td colspan="1"><%= (@sum[:special_paid_time]) %></td>
                    <td colspan="1"><%= (@sum[:actual_time]) %></td>
                    <td colspan="1"><%= (@sum[:deduction_time]) %></td>
                </tr>
            </tbody>
        </table>
    </div>
    <% end %>
</div>

app/views/attendances/check.js.erb
$('#errors').html("<%= j(render 'layouts/errors', errors: @errors) %>");

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<%# javascript_pack_tag 'attendances/index'%>

<style>
    .title{
        text-align: center;
    }
    .transition{
        font-size: 28px;
        margin-bottom: 10px;
        text-decoration: none;
    }
    a:hover {
        text-decoration: none;
    }
    .bi{
        color: #0060b2;
    }
    table{
        font-size: 14px;
    }
    thead {
        background-color: #0060b2;
        color: #fff;
    }
    table tr th.pb{
        padding-bottom: 21px;
    }
    table tr th.pb2{
        padding-bottom: 10px;
    }
    table, td, th {
        border: 2px #3d3f9e solid;
    }
    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px #3d3f9e solid;
    }
    .border-bottom {
        border-bottom: 2px #3d3f9e solid !important;
    }
    .border-top{
        border-top: none;
    }
    .side-line{
        border-right:none;
    }
    .today{
        background-color: #ffc107;
    }
    .sat {
        color: #0000ff;
        background-color: #9dd7fb;
    }
    .sun{
        color: #FF0000;
        background-color: #9dd7fb;
    }

    button{
        width: 150px;
        border: 1px #3d3f9e solid;
        appearance: none;
        border-radius: 5px;
        background: #0060b2;
        color: #fff;
        padding: 8px 16px;
        font-size: 16px;
    }
</style>

<div class="mx-4 row">
    <!-- 先月・翌月遷移 -->
    <div class="col-4 transition">
        <%= link_to attendances_path('date': @nav_prev) do %>
            <i class="bi bi-arrow-left-circle"></i>
        <% end %>
        <%= format_to(@month,:ym) %>
        <%= link_to attendances_path('date': @nav_next) do %>
            <i class="bi bi-arrow-right-circle"></i>
        <% end %>
    </div>

    <h2 class="col-4 title">
        月勤怠表
    </h2>
</div>

<div id="attd_table">
    <%= render 'table', attendances: @attendances %>
</div>
<div class="clearfix mx-4">
    <div class="float-right">
        <%= form_tag(url_for(:action => 'check'), :remote => true) do %>
            <%= hidden_field_tag :date, @month %>
            <%= submit_tag "チェック" %>
        <% end %>
        <button type="button" class="ml-4" onclick="$('#printModal').modal('show')">帳簿出力</button>
        <button type="button" class="ml-4" onclick="$('#orderModal').modal('show')">オーダー別</button>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">オーダー選択</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: url_for(:action => 'orders') do |f|%>
        <%= f.hidden_field :date, value: @month %>
        <div class="modal-body">
            <% 8.times do |i| %>
                <%= f.collection_select :order_id, @orders, :id, :name, 
                { include_blank: '選択してください'}, { class: 'form-control', name: "attendance_detail[orders][#{i}]"} %>
            <% end %>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "オーダー出力", {class: "btn btn-primary"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="printModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render 'print' ,attendances: @attendances%>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-secondary" onclick="()=> printEl();">印刷</button>
      </div>
    </div>
  </div>
</div>


<script>
    function printEl()
    {
        var printAria = document.getElementById('print_area');

        var newWin = window.open('', 'Print-Window');

        newWin.document.open();

        const front_content = function() 
        {
            <html>
            <head>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>    
            </head>
            <body onload="window.print()">
            <style>
                .title{
                    text-align: center;
                }
                .transition{
                    font-size: 28px;
                    margin-bottom: 10px;
                    text-decoration: none;
                }
                a:hover {
                    text-decoration: none;
                }
                .bi{
                    color: #0060b2;
                }
                table{
                    font-size: 14px;
                }
                thead {
                    background-color: #0060b2;
                    color: #fff;
                }
                table tr th.pb{
                    padding-bottom: 21px;
                }
                table tr th.pb2{
                    padding-bottom: 10px;
                }
                table, td, th {
                    border: 2px #3d3f9e solid;
                }
                .table thead th {
                    vertical-align: bottom;
                    border-bottom: 2px #3d3f9e solid;
                }
                .border-bottom {
                    border-bottom: 2px #3d3f9e solid !important;
                }
                .border-top{
                    border-top: none;
                }
                .side-line{
                    border-right:none;
                }
                .today{
                    background-color: #ffc107;
                }
                .sat {
                    color: #0000ff;
                    background-color: #9dd7fb;
                }
                .sun{
                    color: #FF0000;
                    background-color: #9dd7fb;
                }
            
                button{
                    width: 150px;
                    border: 1px #3d3f9e solid;
                    appearance: none;
                    border-radius: 5px;
                    background: #0060b2;
                    color: #fff;
                    padding: 8px 16px;
                    font-size: 16px;
                }
            </style>
        }

        newWin.document.write(front_content+printAria.innerHTML+'</body></html>');

        newWin.document.close();

        setTimeout(function(){newWin.close();},10);
    }
</script>

app/views/attendances/month.html.erb
<%= link_to @month.prev_month.strftime("%Y/%m"), month_attendances_path('date': @nav_prev) %>
<%= @month.strftime("%Y/%m") %>
<%= link_to @month.next_month.strftime("%Y/%m"), month_attendances_path('date': @nav_next) %>

<table>
    <thead>
        <tr>
            <th rowspan="2", colspan="1">日</th>
            <th rowspan="2", colspan="1">曜日</th>
            <th rowspan="2", colspan="3">時刻</th>
            <th rowspan="1", colspan="7">時間内訳</th>
            <th rowspan="2", colspan="1">摘要</th>
        </tr>
        <tr>
            <th rowspan="1", colspan="1">作業</th>
            <th rowspan="1", colspan="1">休憩</th>
            <th rowspan="1", colspan="1">稼働</th>
            <th rowspan="1", colspan="1">有給(一般)</th>
            <th rowspan="1", colspan="1">有給(特別)</th>
            <th rowspan="1", colspan="1">実働</th>
            <th rowspan="1", colspan="1">控除</th>
        </tr>
    </thead>
    <tbody>
        <% (@month.beginning_of_month..@month.end_of_month).each do |month| %>
        <tr>
            <td><%= month.strftime("%d") %></td>
            <td><%= month.strftime("#{@dw[month.wday]}") %></td>
            <td></td>
            <td>～</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <% end %>
    </tbody>
</table>


<button type="button">チェック</button>
<button type="button">帳簿出力</button>
<button type="button">オーダー別</button>

app/views/attendances/new.html.erb
<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/orders.js.erb
$('#attd_table').html("<%= j(render 'table', attendances: @attendances) %>");

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @attendance.employee_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @attendance.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @attendance.end_time %>
</p>


<p>
  <strong>Work content:</strong>
  <%= @attendance.work_content %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/week.html.erb
<div>
    <div class="ue">
        <%= link_to "＜" ,week_attendances_path('date':@first_day.ago(1.weeks).strftime("%Y%m%d")), class:"yazirusi"%>
        <%= link_to "＞" ,week_attendances_path('date':@first_day.since(1.weeks).strftime("%Y%m%d")), class:"yazirusi mar"%>
    </div>
    <table class="table table-striped-columns">
        <thead>
            <tr>
                <% (@first_day.to_date..@last_day.to_date).each do |week| %>
                    <th>
                        <%= week.strftime("#{@dw[week.wday]}") %><br />
                        <%= week %>
                    </th>
                <% end %>
            </tr>
        </thead>
            
        <tbody>
            <tr>
                <% (@first_day.to_date..@last_day.to_date).each do |week| %>
                <% @attendance = Attendance.includes(:attendance_details).references(:attendance_details).find_by(base_date: Date.today, employee_id: @employee.id) %>
                    <td>ueda</td>
                <% end %>
            </tr>
        </tbody>
    </table>
</div>